import React from 'react'
import Head from 'next/head'
import Footer from '../Navigation/Footer'
import Header from '../Navigation/Header'

export default function Layout({children}) {
    return (
        <div>
            <Head>
                <title>Justfields Demo</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet" />

            </Head>
            <Header />
            <main>
                {children}
            </main>
            <Footer />
        </div>
    )
}
